---
title: "MGD5and6_notebook"
author: "Erika Carlson"
format: html
editor_options: 
  chunk_output_type: console
---

------

This document contains research notes and code generated by:

> **Erika R. Carlson**  
> Pharmacology & Toxicology PhD Student  
> University of Texas at Austin  
> erika.carlson@utexas.edu

------

# Subjects for Iba1 IHC rounds

```{r}
subjects <- read_csv("data/subjects.csv") %>% filter(exclude == "N")

set.seed(223)

ihc_1_num <- sample(subjects$subject, size = 24, replace = FALSE)

ihc_1 <- subjects %>% filter(subject %in% ihc_1_num) %>% arrange(group, sex)
ihc_2 <- subjects %>% filter(!subject %in% ihc_1_num) %>% arrange(group, sex)

# write_csv(ihc_1, "/Users/erc2866/Library/CloudStorage/Box-Box/Nixon Lab/Lab Member Data Files/Erika/MGD/MGD5and6/ihc_iba1_1.csv")
# write_csv(ihc_2, "/Users/erc2866/Library/CloudStorage/Box-Box/Nixon Lab/Lab Member Data Files/Erika/MGD/MGD5and6/ihc_iba1_2.csv")

# check treatment distribution across ihc rounds, rearrange in excel as needed
ihc_1 %>% group_by(group, sex) %>% count()
# move 2 PLX-CON F, 1 PLX-CON M, 1 VEH-CON M from ihc_1
# move 1 PLX-EtOH F from ihc_2

# read in updated files
ihc_1_v2 <- read_csv("/Users/erc2866/Library/CloudStorage/Box-Box/Nixon Lab/Lab Member Data Files/Erika/MGD/MGD5and6/ihc_iba1_1.csv") %>% arrange(group, sex)

ihc_2_v2 <- read_csv("/Users/erc2866/Library/CloudStorage/Box-Box/Nixon Lab/Lab Member Data Files/Erika/MGD/MGD5and6/ihc_iba1_2.csv") %>% arrange(group, sex)

# note which subjects were moved
ihc_1_move <- ihc_1 %>% filter(!subject %in% ihc_1_v2$subject)
ihc_2_move <- ihc_2 %>% filter(!subject %in% ihc_2_v2$subject)
```





```{r}
#| echo: false
2 * 2
```

The `echo: false` option disables the printing of code (only output is displayed).
